# Generated by Django 4.1.1 on 2022-09-26 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('category_slug', models.SlugField(blank=True, default='#', editable=False)),
                ('category_color', models.CharField(default='blue', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_name', models.CharField(max_length=100)),
                ('listing_description', models.TextField(max_length=100)),
                ('listing_seo_name', models.SlugField(editable=False, unique=True)),
                ('listing_original_url', models.CharField(default='#', max_length=200)),
                ('listing_category', models.ManyToManyField(to='core.cat')),
            ],
        ),
    ]
