# Generated by Django 4.1.1 on 2022-09-24 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_name', models.CharField(max_length=100)),
                ('listing_description', models.TextField(max_length=500)),
                ('listing_seo_name', models.SlugField(blank=True, default='#', editable=False, unique=True)),
            ],
        ),
    ]
